export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  EMPLOYEES: '/employees',
  CLIENTS: '/clients',
  PROJECTS: '/projects',
  ALLOCATIONS: '/allocations',
  RESOURCE_PLANNER: '/resource-planner',
  BENCH: '/bench',
  REPORTS: '/reports/employees',
  DEPARTMENTS: '/departments',
  DESIGNATIONS: '/designations',
  SKILLS: '/skills',
  ROLES: '/settings/roles',
  AUDIT_LOGS: '/audit-logs',
  USERS: '/users',
  UNAUTHORIZED: '/unauthorized',
  SERVER_ERROR: '/server-error',
  NOT_FOUND: '*',
} as const;
